### ISSUE TITLE
大佬，你这个方案可以用CH340烧录CC2652P的固件吗

### ISSUE THREAD

**Issue by 1006867586** [cyijun/OpenZ3Gateway#7]
RT，已焊接但不知道能否用CH340来烧录

**Comment by cyijun** [comment]
> RT，已焊接但不知道能否用CH340来烧录

@1006867586 可以的，这个模块带bootloader，我也把串口引出来了

**Comment by 1006867586** [comment]
非常感谢，能给个联系方式吗，我不知道哪些针脚要短接，在iobroker论坛上看到的你的帖子，折腾了好久，难在了固件烧录这步




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 上午8:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cyijun/OpenZ3Gateway] 大佬，你这个方案可以用CH340烧录CC2652P的固件吗 (Issue #7)





  
RT，已焊接但不知道能否用CH340来烧录
  
@1006867586 可以的，这个模块带bootloader，我也把串口引出来了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GWan1234** [comment]
![9AFF841A-224F-4057-A28E-A1E9988E3A33](https://user-images.githubusercontent.com/64321391/147722159-9c770a48-23ac-4be2-aa18-96ec4fdbc3c6.jpeg)
这个就是340烧录接口图吧，对着原理图找到引脚就行了。图中烧的是esp，2652p往右第一个白色接口是刷zb的吧。
> 非常感谢，能给个联系方式吗，我不知道哪些针脚要短接，在iobroker论坛上看到的你的帖子，折腾了好久，难在了固件烧录这步
> […](#)

**Comment by cyijun** [comment]
@1006867586 @Tao173 在上电之前按住BSL按钮就能进烧录模式了，短接也太不优雅了😂

**Comment by 1006867586** [comment]
不用短接吗我用的是ch340g，用TI的烧录软件Flash Programmer 2可以识别进入了BSL，就是显示Timed out waiting for ACK/NAK.No response from device。我那个ch340g只引出了5v，GND，RXD和TXD，IO0和RST没连（是因为这个吗）






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 中午1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cyijun/OpenZ3Gateway] 大佬，你这个方案可以用CH340烧录CC2652P的固件吗 (Issue #7)





 
@1006867586 @Tao173 在上电之前按住BSL按钮就能进烧录模式了，短接也太不优雅了😂
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1006867586** [comment]
![1WP2S209$QO4) $I}AYB99](https://user-images.githubusercontent.com/30772119/147725648-51e22a08-8c01-44a6-94f8-ceabca455b78.png)

**Comment by cyijun** [comment]
> 不用短接吗我用的是ch340g，用TI的烧录软件Flash Programmer 2可以识别进入了BSL，就是显示Timed out waiting for ACK/NAK.No response from device。我那个ch340g只引出了5v，GND，RXD和TXD，IO0和RST没连（是因为这个吗）
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Chen ***@***.***&gt;; 发送时间: 2021年12月30日(星期四) 中午1:06 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [cyijun/OpenZ3Gateway] 大佬，你这个方案可以用CH340烧录CC2652P的固件吗 (Issue #7) @1006867586 @Tao173 在上电之前按住BSL按钮就能进烧录模式了，短接也太不优雅了😂 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

@1006867586 康康是不是串口接反了？好像是只需要接txrx和电源的，实在不行你可以做一套我首页上叫AUMST的那个ch340自动上传电路板试试，跟图片里的原理是一样的。我最近期末考试可能没啥时间看这个，不好意思🤣

**Comment by 1006867586** [comment]
好的，感谢大佬，祝考试顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2021年12月30日(星期四) 晚上7:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cyijun/OpenZ3Gateway] 大佬，你这个方案可以用CH340烧录CC2652P的固件吗 (Issue #7)





  
不用短接吗我用的是ch340g，用TI的烧录软件Flash Programmer 2可以识别进入了BSL，就是显示Timed out waiting for ACK/NAK.No response from device。我那个ch340g只引出了5v，GND，RXD和TXD，IO0和RST没连（是因为这个吗）
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Chen @.&gt;; 发送时间: 2021年12月30日(星期四) 中午1:06 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [cyijun/OpenZ3Gateway] 大佬，你这个方案可以用CH340烧录CC2652P的固件吗 (Issue #7) @1006867586 @Tao173 在上电之前按住BSL按钮就能进烧录模式了，短接也太不优雅了😂 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
@1006867586 康康是不是串口接反了？好像是只需要接txrx和电源的，实在不行你可以做一套我首页上叫AUMST的那个ch340自动上传电路板试试，跟图片里的原理是一样的。我最近期末考试可能没啥时间看这个，不好意思🤣
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1006867586** [comment]
可以用ch340来焊接，是我没有用跳线帽接2652的电源，目前zigbee和8266的固件都烧录了，还有个问题，就是我不知道正常运行需要用跳线帽短接哪些针脚，大佬能否上张照片让我少走些弯路，谢谢了

**Comment by 1006867586** [comment]
大佬是这样的，目前我固件都烧录了，8266也配网了，群晖上也搭建了homeassistant和MQTT，都是正常运行，我是用无线连接的，tcp端口1234是可以通的，目前就困扰在搭建zigbee2mqtt的时候，应该是8266与cc2652没有建立通信的原因，zigbee2mqtt启动不了，软件方面的资料我可以在网上查资料，硬件方面我是小白，现在就差临门一脚了，希望大佬能够帮助我，感谢

**Comment by cyijun** [comment]
> 大佬是这样的，目前我固件都烧录了，8266也配网了，群晖上也搭建了homeassistant和MQTT，都是正常运行，我是用无线连接的，tcp端口1234是可以通的，目前就困扰在搭建zigbee2mqtt的时候，应该是8266与cc2652没有建立通信的原因，zigbee2mqtt启动不了，软件方面的资料我可以在网上查资料，硬件方面我是小白，现在就差临门一脚了，希望大佬能够帮助我，感谢

用短接帽按图里的方式短接两对针就好了
![image](https://user-images.githubusercontent.com/42707013/158336079-cfbdf824-c148-4821-818b-7c25f4124d19.png)

**Comment by 1006867586** [comment]
非常感谢，已经连上
![image](https://user-images.githubusercontent.com/30772119/158381193-f12f7d4f-7f40-409e-bf05-dc414fba041f.png)
目前是这样连接的：
![image](https://user-images.githubusercontent.com/30772119/158384195-ef56ee32-82f2-40be-98c8-64ac71355e2c.png)

是用无线连的，有个bug不知道是不是我的操作不对，就如这个帖子https://bbs.hassbian.com/thread-13401-1-1.html 说的，ESP的TX连着就不行，只接5V电源加上如图的短接只要ESP_TX接ZGB_RX就启动不了
